title: From Fish to Physician
baseURL: https://www.kidneyfish.net
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 8
googleAnalytics: 'UA-165990856-1'
enableRobotsTXT: yes
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"] # added Jan 2022
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  body_classes: avenir bg-near-white
  description: A blog about clinically-relevant kidney physiology
  # facebook: ''
  favicon: /images/favicon.ico # put into static folder
  featured_image: /images/homepage.jpg
  # github: ''
  # gitlab: ''
  # instagram: ''
  # linkedin: ''
  # mastodon: ''
  recent_posts_number: 4
  # rss: ''
  # site_logo: /images/favicon.ico - REMOVED Jan 2022
  # slack: ''
  # stackoverflow: ''
  twitter: https://twitter.com/renalrob
  twitterAuthor: '@renalrob' # added 2022 - for Twitter cards
  twitterImg: /images/twittercard.jpg # addedd 2022 - for Twitter cards
  # youtube: ''
  show_reading_time: true
  custom_css: [RWH_kidneyfish.css]
  env: production
  
# Jan 2022: to add meta codes for Twitter cards, edit themes/gohugo-theme-ananke/layouts/partials/head-additions.html
# Could also move the MaxJax scripts here - ? with defer
